services:
  postgres:
    image: postgres:16-alpine
    container_name: velozity_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: velozity_user
      POSTGRES_PASSWORD: velozity_pass
      POSTGRES_DB: velozity_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U velozity_user -d velozity_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
